apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-web
  labels:
    app: pride-web
spec:
  replicas: $k8s_replicas
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pride-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: $k8s_rollingupdate_maxUnavailable
  template:
    metadata:
      labels:
        app: pride-web
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      volumes:
        - name: filebeat-config
          configMap:
            name: $FILEBEAT_CONFIG_MAP
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: logvolume
          emptyDir: {}
      containers:
        - name: pride-web
          image: $IMAGE
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /pride
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pride
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: logvolume
              mountPath: /logs
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.8.0
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: logvolume
              mountPath: /logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
---
apiVersion: v1
kind: Service
metadata:
  name: pride-web-service
spec:
  selector:
    app: pride-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
