apiVersion: apps/v1
kind: Deployment
metadata:
  name: pride-web
  labels:
    app: pride-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pride-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: pride-web
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: pride-web
          image: $IMAGE
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pride-web-service
spec:
  selector:
    app: pride-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
